Incremental search
696b/ChatSpace pull request #12
Opened 2019-05-25 11:40 UTC by 696b

# WHAT
インクリメンタルサーチの実装

# WHY
グループにユーザーを追加する際に必要だから

2019-05-25 11:50 UTC, i-date reviewed
ご提出ありがとうございます！コメントいたしました^^
また、実装機能の動作を確認するため、GyazoGifなどで動画を載せていただけないでしょうか？

2019-05-25 11:50 UTC, i-date commented on app/assets/javascripts/user_search.js
> +      $("#user-search-result").empty();
3行目で以下のように変数設定しているので使用するか、そうでなければ3行目を削除しましょう。
`var search_list = $("#user-search-result");`

2019-05-25 11:50 UTC, i-date commented on app/assets/javascripts/user_search.js
> +
この空行は削除しましょう。

2019-05-25 11:50 UTC, i-date commented on app/assets/javascripts/user_search.js
> +  var user_name = $(this).attr('data-user-name');
49-50行目はカスタムデータ属性を使用している利点が薄れてしまうので、attrではなくdataメソッドを使いましょう。
例：`attr('data-user-id')`は`data('user-id')`と記述できます。

2019-05-25 11:50 UTC, i-date commented on app/assets/javascripts/user_search.js
> +  var html = `<div class='chat-group-user clearfix js-chat-member' id='${user_id}'>
function使用して関数化して切り出してあげたほうが可読性が良くなると思います。

2019-05-25 11:50 UTC, i-date commented on app/assets/stylesheets/modules/group.scss
> +  // border: 1px solid #ddd;
こちら不要でしたら削除しましょう。

2019-05-25 11:50 UTC, i-date commented on app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?)',"%#{params[:keyword]}%")
current_userは含めないという条件を追加してあげましょう。

2019-05-25 11:50 UTC, i-date commented on app/controllers/users_controller.rb
> +    # end
26-29行目は削除しましょう。

2019-05-25 11:52 UTC, 696b commented
https://gyazo.com/20d0fe6ef12a4c42c909191316d03686

動作の確認動画です。

2019-05-26 06:28 UTC, 696b commented on app/assets/javascripts/user_search.js
> +  var user_name = $(this).attr('data-user-name');
var user_id = $(this).data('user-id');
var user_name = $(this).data('user-name');
に変更しました。

2019-05-26 06:29 UTC, 696b commented on app/assets/javascripts/user_search.js
> +  var html = `<div class='chat-group-user clearfix js-chat-member' id='${user_id}'>
function appendMemberHTML(id, name){
    var html = `<div class='chat-group-user clearfix js-chat-member' id='${user_id}'>
    <input name='group[user_ids][]' type='hidden' value='${user_id}'>
    <p class='chat-group-user__name'>${user_name}</p>
    <div class='user-search-remove chat-group-user__btn chat-group-user__btn--remove js-remove-btn'>削除</div>
  </div>`
  $("#chat-group-users").append(html);
  }
  appendMemberHTML(user_id, user_name);

に変更しました。

2019-05-26 06:30 UTC, 696b commented on app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?)',"%#{params[:keyword]}%")
.where.not(id: current_user.id)　を追加しました。

2019-05-26 06:35 UTC, 696b commented
# WHAT
検索結果からcurrent_userを削除
空行を削除
変数を関数化

#WHY
自身をグループに追加はしないため。
可読性を高めるため

2019-05-26 06:38 UTC, nagatomokent commented on app/assets/javascripts/user_search.js
> +    <p class="chat-group-user__name">${msg}</p>
インデント整えましょう

2019-05-26 06:44 UTC, 696b commented on app/assets/javascripts/user_search.js
> +    <p class="chat-group-user__name">${msg}</p>
# WHAT 
user_search.jsの49-53行目のインデントを以下のように整えました。

<div class='chat-group-user clearfix js-chat-member' id='${user_id}'>
                  <input name='group[user_ids][]' type='hidden' value='${user_id}'>
                  <p class='chat-group-user__name'>${user_name}</p>
                  <div class='user-search-remove chat-group-user__btn chat-group-user__btn--remove js-remove-btn'>削除</div>
                </div>`


# WHY
可読性を高めるため。

2019-05-26 06:48 UTC, ghost requested changes

2019-05-26 06:48 UTC, hiroki5123 commented on app/views/messages/index.html.haml
>        -# %p.border{border: solid 10px #eeeee }
不要であれば削除しましょう

2019-05-26 06:48 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +        %li.member  name
ここってまだ実装しない感じですか？

2019-05-26 06:48 UTC, hiroki5123 commented on app/assets/stylesheets/_main.scss
> +
空行が1行ほどでいいと思います

2019-05-26 06:48 UTC, hiroki5123 commented on app/assets/stylesheets/_main.scss
> +
空行が1行ほどでいいと思います

2019-05-26 06:48 UTC, hiroki5123 commented
修正分をpushしてください〜

2019-05-26 06:51 UTC, 696b commented on app/views/messages/index.html.haml
> +        %li.member  name
してません

2019-05-26 08:04 UTC, 696b commented
# WHAT
messages/index.haml.htmlに - @members.each do |member|を追加。
user_search.jsに$(document).on("turbolinks:load", function(){　}) を追加。

# WHY
追加したメンバーをビューに表示できるようにするため。
ページ遷移時にイベントを発火できるようにするため。

2019-05-26 08:08 UTC, ghost requested changes

2019-05-26 08:08 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +        // });
必要なければ削除してください

2019-05-26 08:10 UTC, 696b commented
# WHAT 
message.jsのコメントアウトを削除

# WHY
可読性を高めるため。

2019-05-26 08:14 UTC, kuroko918 commented on Gemfile
> +gem 'pry-rails'
これはproduction環境では使用しないので、
group development, test do
の中に入れておいて下さい。

2019-05-26 08:15 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +  $(function() {
一行目と被っているので消しておきましょう！

2019-05-26 08:15 UTC, kuroko918 commented on app/assets/javascripts/user_search.js
> +  $(function() {
こちらも一行目と被っているので消しておきましょう！

2019-05-26 08:18 UTC, 696b commented on Gemfile
> +gem 'pry-rails'
gemfileを以下のように編集しました。
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'rspec-rails','~> 3.5'
  gem 'rails-controller-testing'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'mini_magick'
  gem 'pry-rails'
end

2019-05-26 08:19 UTC, 696b commented on app/assets/javascripts/message.js
> +  $(function() {
message.jsを以下のように編集しました。

$.ajax({
          url: url,
          type: "POST",
          data: formData,
          dataType: 'json',
        })

2019-05-26 08:27 UTC, 696b commented
# WHAT 
message.jsを編集

# WHY
$(document).on("turbolinks:load", function(){ を追加したことで重複した部分があったため。

2019-05-26 08:30 UTC, nagatomokent commented
lgtm

2019-05-26 08:31 UTC, merged